### ISSUE TITLE
I2s to DAC is broken?

### ISSUE THREAD

**Issue by pjmi1** [pschatzmann/arduino-flite#1]
Thank you for your code.

I can't get the example text_to_speach_analog to work (I2S through the ESP32 DAC output, ie using I2S_MODE_DAC_BUILT_IN) - it does not work for the latest Arduino ESP32 core v. 2.0.3

I tested this on an external amplifier that works fine using non-I2S output to the ESP32 DAC.

The text_to_speach_analog works fine - using an external I2S amplifier module - the speech output is surprisingly good.

I assume this issue is due to this: https://github.com/espressif/arduino-esp32/issues/5938#issuecomment-1125755001 
though this was apparently fixed and closed!

Please can you confirm this / suggest solutions?

Thanks in advance

**Comment by pschatzmann** [comment]
The issue with the DAC has been resolved in 2.0.3.
I think the issue here is the missing sample rate and missing logic to provide it automatically (as indicated).
I just committed a correction. You can also try with your current code by entering the sample rate 8000

Can you help me to test my change ?

**Comment by pjmi1** [comment]
Thanks, but still no output.
I can vaguely hear a very faint buzz at the word period expected, like it is outputting very small values? 
I assume it is sending the same data to both L/R channels GPIO 25 and 26?

**Comment by pschatzmann** [comment]
I think I will delete the example from here: It is better do the output via the Arduino-Audio-Tools project which handles the additional necessary conversion correctly... 
So it would be the stream example from this project where you pass a [AnalogAudioStream](https://pschatzmann.github.io/arduino-audio-tools/html/classaudio__tools_1_1_analog_audio_stream.html#af6075d89ca3d792b0fb99256143706d5)  which will do the output.
Don't forget to setup the AnalogAudioStream with the correct audio information...

**Comment by pjmi1** [comment]
I'll have a look at that, thanks.
Is the problem: (from the ESP32 docs) "Output I2S data to built-in DAC, no matter the data format is 16bit or 32 bit, the DAC module will only take the 8bits from MSB".
...and if so, is there a way around this in your flite code?

**Comment by pschatzmann** [comment]
You can use the callback method and do this correction (and I2S setup and output) in your code. But honestly just using the AnalogAudioStream is much less work and also less complicated, because it automatically handles this correctly.

**Comment by pjmi1** [comment]
Hi again.
So, I attempted to use the AnalogAudioStream, borrowing from the streams-generator-analog.ino example (which works fine).
Unfortunately, I get loud screeching birds! Please can you say where I have gone wrong? Maybe the output rate is much too high?
```
#include "AudioTools.h"
#include "flite_arduino.h"

AnalogAudioStream out; 
Flite flite(new FliteOutputStream(out));

void setup()
{
  Serial.begin(115200);
  AudioLogger::instance().begin(Serial, AudioLogger::Info);  // This serial print works fine
  auto config = out.defaultConfig(TX_MODE);
  config.sample_rate = 44100;   // 8000 also tried - same result
  out.begin(config);
}

void loop()
{
    const char* hallo ="hallo";
    Serial.println(hallo);
    flite.say(hallo);    
    delay(1000);
}

```

**Comment by pschatzmann** [comment]
In [this example](https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-webserver/streams-flite-webserver_wav/streams-flite-webserver_wav.ino) I am using 1 channel, 8000 samples/second, 16 bits so:
- cfg.sample_rate = 8000;
- cfg.channels = 1;
- cfg.bits_per_sample = 16;  // this is not necessary because it is the default setting
should work...

I did not double check but shouln't it be just
Flite flite(out);
