### ISSUE TITLE
Voice change issue

### ISSUE THREAD

**Issue by gnpaone** [pschatzmann/arduino-flite#3]
As mentioned, flite contains lots of voices but can you explain how to change voice in code?
I saw in header files too there's a function. Please explain
https://github.com/pschatzmann/arduino-flite/blob/45f3451e74995dbc2030d275c0dc6edfc299ed25/src/flite_arduino.h#L69-L77

**Comment by pschatzmann** [comment]
You can try one of the following:

                setVoice(register_cmu_us_kal16(nullptr));
                setVoice(register_cmu_us_slt(nullptr));
                setVoice(register_cmu_us_rms(nullptr));
                setVoice(register_cmu_us_awb(nullptr));
                setVoice(register_cmu_time_awb(nullptr));

But if I remember right there is not enough of Memory on the ESP32 for this to work...

**Comment by gnpaone** [comment]
No, I am using 8MB flash, and the code is uploading good after few additions in the configuration for it to upload
Config: (same case for my ESP32S3 and ESP32 that I use)
`
esp32s3.menu.PartitionScheme.large_5MB=Large 4MB with spiffs (5MB No OTA/1MB SPIFFS)
esp32s3.menu.PartitionScheme.large_5MB.build.partitions=large_5MB
esp32s3.menu.PartitionScheme.large_5MB.upload.maximum_size=5242880
`
`
esp32s3.menu.PartitionScheme.large_4MB=Large 4MB with spiffs (4MB No OTA/1MB SPIFFS)
esp32s3.menu.PartitionScheme.large_4MB.build.partitions=large_4MB
esp32s3.menu.PartitionScheme.large_4MB.upload.maximum_size=3670016
`
`
esp32s3.menu.PartitionScheme.large_8MB=Large 8M Flash (4MB APP/1MB SPIFFS)
esp32s3.menu.PartitionScheme.large_8MB.build.partitions=large_spiffs_8MB
esp32s3.menu.PartitionScheme.large_8MB.upload.maximum_size=3670016
`
(I use the 2nd config for my AI-thinker Audiokit ESP32 too as it has only 4MB flash and still voices upload fine and code executes)

The code uploads fine and executes but it's the cg voice I need help with (kal voice which is a diphone works good in my edited partition config too) (I am trying to use slt voice). As you can see in https://github.com/pschatzmann/arduino-flite/pull/4 the execution for cg voice is missing (I am not sure where the problem lies so need help)

Successfully uploaded:
![image](https://user-images.githubusercontent.com/78990165/180923270-df6e0993-8750-42ea-b465-2fd7ad306cf7.png)

Tried using slt voice like this:
![image](https://user-images.githubusercontent.com/78990165/180923388-b5c1bf69-b1ba-4d09-b7bc-1b1e9b37fe2f.png)

**Comment by deladriere** [comment]
``` 
void setup()
{
  Serial.begin(115700);
  flite.setVoice(register_cmu_us_kal(nullptr));
}
```
works fine for me but I have only 4MB of flash and I wish I could try other voices  like the cmu_us_fem voice

**Comment by gnpaone** [comment]
There is a way you can test it (similar to I did). Based on your Arduino ide installation type (Microsoft store or exe - Admin installation/Local installation), First close Arduino if it's open, I am using Microsoft store version and using 2.0.4 version of esp32 boards installation so go to C:\Users\<username>\Documents\ArduinoData\packages\esp32\hardware\esp32\2.0.4\tools\partitions and paste this file there
[large_4MB.csv](https://github.com/pschatzmann/arduino-flite/files/9194374/large_4MB.csv)
this file basically contains the partition configuration:
```
# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x5000,
otadata,  data, ota,     0xe000,  0x2000,
app0,     app,  ota_0,   0x10000, 0x380000,
spiffs,   data, spiffs,   0x390000,0x70000,
```
then go to C:\Users\<username>\Documents\ArduinoData\packages\esp32\hardware\esp32\2.0.4\boards.txt and paste this in between partitions submenu list of esp32 dev module t(assuming that you are using esp32 devmodule)
```
esp32.menu.PartitionScheme.large_4MB=Large 4MB with spiffs (4MB No OTA/1MB SPIFFS)
esp32.menu.PartitionScheme.large_4MB.build.partitions=large_4MB
esp32.menu.PartitionScheme.large_4MB.upload.maximum_size=3670016
```
Try to use i2s rather than audiokit because audiokit takes more storage for other voices which may not fit in 4mb flash. You can use audiokit too with above config or below extreme case config (maximum app size)
```
# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x5000,
otadata,  data, ota,     0xe000,  0x2000,
app0,     app,  ota_0,   0x10000, 0x3C0000,
spiffs,   data, spiffs,   0x3D0000,0x30000,
```
and `esp32.menu.PartitionScheme.large_4MB.upload.maximum_size=3932160`. This extreme case also works with i2s and audiokit. If you are using exe local installation then I think the folder is in C:\Users\<username>\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4
Now open Arduino and you can find a new entry under Tools/Partition Scheme after selecting esp32 devmodule board, select that new entry and try it. Use kal voice first with this new configuration for checking if it works and then other voice.
My boards.txt:
[boards.txt](https://github.com/pschatzmann/arduino-flite/files/9194441/boards.txt)

**Comment by gnpaone** [comment]
I want to use voices with .flitevox extension directly similar to original flite. Please help 🥺
@pschatzmann @festvox @awbcmu

**Comment by steeley** [comment]
I've tried the modification for 4 meg app but I can't gat Amy of the other voices to load because there is not enough ram .
I have 8 meg esp32-s3 4 meg app set 
how can I get this to work?

**Comment by pschatzmann** [comment]
No! - I never managed to have different voices. It might be possible to have it with PSRAM working, but I never tried.

If you want to use different voices I suggest to use my adapted espeak-ng library

**Comment by steeley** [comment]
thanks. 
espeak looks good. Can it do phonemes? I don't see an example, but there is a mention of phonemes in the Oxygen doc.

**Comment by pschatzmann** [comment]
I honestly don't know because I never used this functionality. The description of the original project however says:
- SSML (Speech Synthesis Markup Language) is supported (not complete), and also HTML.
If you figured out how this works, please share your result
