### ISSUE TITLE
voice repeats last word

### ISSUE THREAD

**Issue by steeley** [pschatzmann/arduino-flite#6]
This code from the examples compiled on ESP32-s3(4meg, 3meg app) plays the voice ok except at the end it repeats the last word. The repeated word is also slightly different/distorted/wobbly. I am using an i2s PCM1502A DAC which works well.
default i2s pins for the ESP32-s3 dev kit are wired as:
lrclk=  gpio7 = pin7
blk = gpio6 = pin6 
data = gpio8 = pin12

Is there a workaround for this strange repeat?

```
#include "flite_arduino.h"
#include "AudioTools.h"  // https://github.com/pschatzmann/arduino-audio-tools
//#include "AudioLibs/AudioKit.h"

I2SStream out; // Replace with desired class e.g. AudioKitStream, AnalogAudioStream etc.
Flite flite(out);


void setup(){
  Serial.begin(115200);
  AudioLogger::instance().begin(Serial, AudioLogger::Info);

  // start data sink
  auto cfg = out.defaultConfig();
  cfg.sample_rate = 8000;
  cfg.channels = 1;
  cfg.bits_per_sample = 16;
  out.begin(cfg);
}

// Arduino loop  
void loop() {  
  Serial.println("providing data...");
  flite.say("Hallo, my name is Alice");
  delay(5000);
}
```

**Comment by pschatzmann** [comment]
I can't reproduce your issue. However I am getting a strong white noise at the end of some words. 
Maybe your dac does not like suddenly not to get any data any more. The following works perfectly for me 

```
  void loop() {  
    Serial.println("providing data...");
    flite.say("Hallo, my name is Allice,");
    out.writeSilence(5*2*8000);  // 5 sec silence 
  }
```

**Comment by steeley** [comment]
the writeSilence function seems to solve the problem
thanks.
