### ISSUE TITLE
Create an output mode for streaming into a fixed RAM buffer

### ISSUE THREAD

**Issue by jhud** [pschatzmann/arduino-flite#7]
It’s already a miracle that this code runs on an ESP32. But I get out-of-memory errors on this platform when the phrase grows too long. My output is to I2S. 

It would be great if the library could stream into a small RAM buffer as the audio is generated, instead of allocating audio space on the heap. That way, it could say arbitrarily-long phrases. 

Before I start modifying the code, is this feature feasible, or possible with some existing configuration?

**Comment by pschatzmann** [comment]
I guesss the best way to deal with the limited RAM is to use PSRAM.

**Comment by jhud** [comment]
That would definitely be easiest if I had a choice of hardware, but I’d like it to run on standard WROOM-based dev boards. Do you think the lack of streaming is more of a limitation of Flite itself, or just of the I2S output code?

**Comment by pschatzmann** [comment]
I am not really sure what problem you are referring to. 
When I tested, most of the instruments were working.

What exactly do you mean with "the phrase grows too long". You would really need to find out where exactly you run into issues.

**Comment by jhud** [comment]
I'm running an ESP32 with 196K RAM free. 
When I say the following phrase using the library, it works fine: "say hello hello hello hello hello hello". When I add a "hello", it crashes, presumably from running out of heap. I would like to make this library use a fixed buffer if possible, instead of using an arbitrary amount of heap, which it seems to be doing. I'm not sure how much work that would be.

**Comment by pschatzmann** [comment]
feel free to implement this yourself. I an not sure however if this will help in any way since the ram is limited, if you used a fixed buffer or not.

The preferred way on an ESP32 [is to use PSRAM](https://www.pschatzmann.ch/home/2022/05/30/esp32-and-psram/) and this does not need any change of this library.

An alternative way to deal with this, would be to feed individual words instead of sentences.

**Comment by jhud** [comment]
My eventual solution was to "dead bug" a PSRAM chip onto the ESP32. And then use ESP32-S3 for future hardware revisions ![tempImagedcZiyh](https://github.com/user-attachments/assets/7c4f5a0f-0303-4bd1-ac32-278bcf893b01)
