### ISSUE TITLE
ESP32 Audio Kit Board-text_to_speach_stream-Error AudioKitStream Does Name A Type

### ISSUE THREAD

**Issue by mrmonteith** [pschatzmann/arduino-flite#8]
I'm using Arduino IDE 2.3.2 and latest of your Audio Tools, Arduino Flite, Audio Driver.
Using the example: [text_to_speach_stream](https://github.com/pschatzmann/arduino-flite/tree/main/examples/text_to_speach_stream)

The way I read this line:
`I2SStream out; // Replace with desired class e.g. AudioKitStream, AnalogAudioStream etc.
`
That I should change it to:
`AudioKitStream  out; // Replace with desired class e.g. AudioKitStream, AnalogAudioStream etc.`

With the original line it compiles.  But with the change I get an error:
`text_to_speach_stream.ino:5:1: error: 'AudioKitStream' does not name a type`

**Comment by pschatzmann** [comment]
You are missing the required import for AudioKitStream which is  by the way obsolete and I do not recommend to use! 

If you have an AudioKit, look at the [corresponding examples in the AudioTools](https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-audiokit) or read the documentation in the [corresponding Wiki](https://github.com/pschatzmann/arduino-audio-tools/wiki/Audio-Boards) on how to use it with the actual functionality.

**Comment by mrmonteith** [comment]
Yeah, I was up until 2am doing some tests.  Of course waiting on compiling in between.  Then I realized the obsolete note and shook my head.  Sorry to bother your time on that part.   To make sure I don't use it I'll remove it.  I'm using an ESP32 AudioKit Board.   Thanks and keep up the great work.
